config/routes.rb
Library::Application.routes.draw do

  resources :book_genres

  resources :authors

  root 'application#index'

  resources :genres

  resources :user_books

  resources :users

  resources :books

  resources :book_infos

  

end

app/models/book_info.rb
#!/bin/env ruby
# encoding: utf-8
class BookInfo < ActiveRecord::Base

  has_many :books
  has_many :book_genres
  has_many :genres, :through => :book_genres

  validates_presence_of :title, :publish_city, :publish_year, :publisher, :pages, :cost, :genres

  AUTHORS = ['Пушкин','Толстой','Стариков','Ролинг','Лермонтов','Гоголь']

end

app/controllers/book_infos_controller.rb
class BookInfosController < ApplicationController
  before_action :set_book_info, only: [:show, :edit, :update, :destroy]

  # GET /book_infos
  # GET /book_infos.json
  def index
    @book_infos = BookInfo.all
  end

  # GET /book_infos/1
  # GET /book_infos/1.json
  def show
  end

  # GET /book_infos/new
  def new
    @book_info = BookInfo.new
    @book = Book.new
  end

  # GET /book_infos/1/edit
  def edit
  end

  # POST /book_infos
  # POST /book_infos.json
  def create
    @book_info = BookInfo.new(book_info_params)
    @book = Book.new

    p 'Creating BookInfo'
    respond_to do |format|
      if @book_info.save
        format.html { redirect_to @book_info, notice: 'Book info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book_info }
      else
        format.html { render action: 'new' }
        format.json { render json: @book_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_infos/1
  # PATCH/PUT /book_infos/1.json
  def update
    respond_to do |format|
      if @book_info.update(book_info_params)
        format.html { redirect_to @book_info, notice: 'Book info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_infos/1
  # DELETE /book_infos/1.json
  def destroy
    @book_info.destroy
    respond_to do |format|
      format.html { redirect_to book_infos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_info
      @book_info = BookInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_info_params
      params.require(:book_info).permit(:title, :author, :publish_city, :publisher, :publish_year, :pages, :cost, :genre_ids => [], :genres => [])
    end
end

app/helpers/book_infos_helper.rb
module BookInfosHelper
end

app/views/book_infos/_form.html.erb
<%= form_for(@book_info) do |f| %>
  <% if @book_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_info.errors.count, "error") %> prohibited this book_info from being saved:</h2>

      <ul>
      <% @book_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Название книги' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'Автор' %><br>
    <%= f.collection_select :author, BookInfo::AUTHORS, :to_s, :to_s %>
  </div>
  <div class="field">
    <%= f.label 'Город издателя' %><br>
    <%= f.text_field :publish_city %>
  </div>
  <div class="field">
    <%= f.label 'Издательство' %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label 'Год издания' %><br>
    <%= f.number_field :publish_year, :min => 1960, :max => DateTime.now.year %>
  </div>

    <div class="field">
      <fieldset>
        <legend>Жанры</legend>
        <div style="padding-left:10px;">
          <% i=0 %>
          <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name do |b| %>
              <% if ((i%3)==0) %>
                  </div><div style="padding-left:10px;">
              <% end %>
              <% i += 1 %>
              <%= b.check_box %>
              <%= b.label %>
          <% end %>
          </div>
      </fieldset>
    </div>

  <div class="field">
    <%= f.label 'Страниц в книге' %><br>
    <%= f.number_field :pages %>
  </div>
  <div class="field">
    <%= f.label 'Цена книги, руб.' %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit 'Создать книгу' %>
  </div>
<% end %>

app/views/book_infos/edit.html.erb
<h1>Editing book_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_info %> |
<%= link_to 'Back', book_infos_path %>

app/views/book_infos/index.html.erb
<h1>Список всех книг</h1>

<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Publish city</th>
    <th>Publisher</th>
    <th>Publish year</th>
    <th>Pages</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @book_infos.each do |book_info| %>
      <tr>
        <td><%= book_info.title %></td>
        <td><%= book_info.author %></td>
        <td><%= book_info.publish_city %></td>
        <td><%= book_info.publisher %></td>
        <td><%= book_info.publish_year %></td>
        <td><%= book_info.pages %></td>
        <td><%= book_info.cost %></td>
        <td><%= link_to 'Show', book_info %></td>
        <td><%= link_to 'Edit', edit_book_info_path(book_info) %></td>
        <td><%= link_to 'Destroy', book_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td rowspan="1">
          <% book_info.books.each do |book| %>
              <%= book.isbn %>: <%= book.place %><br/>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новая книга', new_book_info_path %>

app/views/book_infos/new.html.erb
<div class="table">
  <div class="row">
    <div class="col-md-6">
      <h4>Новая книга</h4>
      <%= render 'form' %>
    </div>
    <div class="col-md-6">
      <h4>новый экземпляр существующей книги</h4>
      <%= render 'books/form' %>
    </div>
  </div>
</div>

<%= link_to 'Back', books_path %>

app/views/book_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book_info.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book_info.author %>
</p>

<p>
  <strong>Publish city:</strong>
  <%= @book_info.publish_city %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book_info.publisher %>
</p>

<p>
  <strong>Publish year:</strong>
  <%= @book_info.publish_year %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @book_info.pages %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @book_info.cost %>
</p>

<%= link_to 'Edit', edit_book_info_path(@book_info) %> |
<%= link_to 'Back', book_infos_path %>