config/routes.rb
Library::Application.routes.draw do

  resources :book_genres

  resources :authors

  root 'application#index'

  resources :genres

  resources :user_books

  resources :users

  resources :books

  resources :book_infos

  

end

app/models/book_genre.rb
#!/bin/env ruby
# encoding: utf-8

class BookGenre < ActiveRecord::Base
  belongs_to :genre
  belongs_to :book_info
end

app/controllers/book_genres_controller.rb
#!/bin/env ruby
# encoding: utf-8
class BookGenresController < ApplicationController
  before_action :set_book_genre, only: [:show, :edit, :update, :destroy]

  # GET /book_genres
  # GET /book_genres.json
  def index
    @book_genres = BookGenre.all
  end

  # GET /book_genres/1
  # GET /book_genres/1.json
  def show
  end

  # GET /book_genres/new
  def new
    @book_genre = BookGenre.new
  end

  # GET /book_genres/1/edit
  def edit
  end

  # POST /book_genres
  # POST /book_genres.json
  def create
    @book_genre = BookGenre.new(book_genre_params)

    respond_to do |format|
      if @book_genre.save
        format.html { redirect_to @book_genre, notice: 'Book genre was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book_genre }
      else
        format.html { render action: 'new' }
        format.json { render json: @book_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_genres/1
  # PATCH/PUT /book_genres/1.json
  def update
    respond_to do |format|
      if @book_genre.update(book_genre_params)
        format.html { redirect_to @book_genre, notice: 'Book genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_genres/1
  # DELETE /book_genres/1.json
  def destroy
    @book_genre.destroy
    respond_to do |format|
      format.html { redirect_to book_genres_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_genre
      @book_genre = BookGenre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_genre_params
      params.require(:book_genre).permit(:genre_id, :book_info_id)
    end
end

app/helpers/book_genres_helper.rb
module BookGenresHelper
end

app/views/book_genres/_form.html.erb
<%= form_for(@book_genre) do |f| %>
  <% if @book_genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_genre.errors.count, "error") %> prohibited this book_genre from being saved:</h2>

      <ul>
      <% @book_genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :book_info %><br>
    <%= f.text_field :book_info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/book_genres/edit.html.erb
<h1>Editing book_genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_genre %> |
<%= link_to 'Back', book_genres_path %>

app/views/book_genres/index.html.erb
<h1>Listing book_genres</h1>

<table>
  <thead>
    <tr>
      <th>Genre</th>
      <th>Book info</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @book_genres.each do |book_genre| %>
      <tr>
        <td><%= book_genre.genre %></td>
        <td><%= book_genre.book_info %></td>
        <td><%= link_to 'Show', book_genre %></td>
        <td><%= link_to 'Edit', edit_book_genre_path(book_genre) %></td>
        <td><%= link_to 'Destroy', book_genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book genre', new_book_genre_path %>

app/views/book_genres/new.html.erb
<h1>New book_genre</h1>

<%= render 'form' %>

<%= link_to 'Back', book_genres_path %>

app/views/book_genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Genre:</strong>
  <%= @book_genre.genre %>
</p>

<p>
  <strong>Book info:</strong>
  <%= @book_genre.book_info %>
</p>

<%= link_to 'Edit', edit_book_genre_path(@book_genre) %> |
<%= link_to 'Back', book_genres_path %>