config/routes.rb
Library::Application.routes.draw do

  resources :book_genres

  resources :authors

  root 'application#index'

  resources :genres

  resources :user_books

  resources :users

  resources :books

  resources :book_infos

  

end

app/models/user_book.rb
#!/bin/env ruby
# encoding: utf-8
class UserBook < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  after_create :update_user_book_count

  def update_user_book_count
    self.user.books_count = UserBook.where(:user => self.user).count
    self.book.status |= Book::STATUS_GIVEN
    self.book.save!
    self.user.save!
  end
end

app/controllers/user_books_controller.rb
#!/bin/env ruby
# encoding: utf-8
class UserBooksController < ApplicationController
  before_action :set_user_book, only: [:show, :edit, :update, :destroy]

  # GET /user_books
  # GET /user_books.json
  def index
    @user_books = UserBook.all
  end

  # GET /user_books/1
  # GET /user_books/1.json
  def show
  end

  # GET /user_books/new
  def new
    @user_book = UserBook.new
  end

  # GET /user_books/1/edit
  def edit
  end

  # POST /user_books
  # POST /user_books.json
  def create
    @user_book = UserBook.new(user_book_params)

    respond_to do |format|
      if @user_book.save
        format.html { redirect_to @user_book, notice: 'User book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_book }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_books/1
  # PATCH/PUT /user_books/1.json
  def update
    respond_to do |format|
      if @user_book.update(user_book_params)
        format.html { redirect_to @user_book, notice: 'User book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_books/1
  # DELETE /user_books/1.json
  def destroy
    @user_book.destroy
    respond_to do |format|
      format.html { redirect_to user_books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_book
      @user_book = UserBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_book_params
      params.require(:user_book).permit(:user_id, :book_id, :expires_at, :status)
    end
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/views/user_books/_form.html.erb
<%= form_for(@user_book) do |f| %>
  <% if @user_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_book.errors.count, "error") %> prohibited this user_book from being saved:</h2>

      <ul>
      <% @user_book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.collection_select :user_id, User.where('books_count<5'), :id, :valid_name %>
  </div>
  <div class="field">
    <%= f.label :book %><br>
    <%= f.collection_select :book_id, Book.where("status&#{Book::STATUS_GIVEN}=0"), :id, :book_ident %>
  </div>
  <div class="field">
    <%= f.label :expires_at %><br>
    <%= f.datetime_select :expires_at %>
  </div>
  <div class="field">
    <%= f.hidden_field :status, :value => 0 %>
  </div>
  <div class="actions">
    <%= f.submit 'Отдать книгу' %>
  </div>
<% end %>

app/views/user_books/edit.html.erb
<h1>Editing user_book</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_book %> |
<%= link_to 'Back', user_books_path %>

app/views/user_books/index.html.erb
<h1>Книги на дом</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th>Expires at</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_books.each do |user_book| %>
      <tr class="<%= "danger" if user_book.expires_at<DateTime.now %>">
        <td><%= user_book.user.valid_name %></td>
        <td><%= user_book.book.book_ident %></td>
        <td><%= user_book.expires_at %></td>
        <td><%= user_book.status %></td>
        <td><%= link_to 'Show', user_book %></td>
        <td><%= link_to 'Edit', edit_user_book_path(user_book) %></td>
        <td><%= link_to 'Destroy', user_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Зафиксировать передачу книги', new_user_book_path %>

app/views/user_books/new.html.erb
<h1>Отдаем книгу:</h1>

<%= render 'form' %>

<%= link_to 'Back', user_books_path %>

app/views/user_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_book.user %>
</p>

<p>
  <strong>Book:</strong>
  <%= @user_book.book %>
</p>

<p>
  <strong>Expires at:</strong>
  <%= @user_book.expires_at %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user_book.status %>
</p>

<%= link_to 'Edit', edit_user_book_path(@user_book) %> |
<%= link_to 'Back', user_books_path %>